17 th com

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -78,6 +78,21 @@ jobs:
           docker pull $ECR_REGISTRY/swarmtaskfrontend:$IMAGE_TAG
 
           # ----------------------------
+          # RECREATE NGINX CONFIG
+          # Swarm configs are immutable — must remove and recreate
+          # on every deploy otherwise stack deploy fails
+          # ----------------------------
+          echo "RECREATING NGINX CONFIG"
+          docker stack rm $STACK || true
+          echo "Waiting for stack to fully remove..."
+          sleep 20
+
+          docker config rm ${STACK}_nginx_conf 2>/dev/null || true
+          docker config rm nginx_conf           2>/dev/null || true
+          docker config create nginx_conf ./nginx.conf
+          echo "nginx_conf created ✓"
+
+          # ----------------------------
           # DEPLOY STACK
           # Swarm rolling update starts here
           # update_config in docker-compose.yml controls this
